<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
<meta name="format-detection" content="telephone=no, address=no, email=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Expires" content="0">
<meta http-equiv="Pragma" content="no-cache">
<meta name="Author" content="대한진단검사의학회 CME">
<meta name="Keywords" content="대한진단검사의학회 CME">
<meta name="description" content="대한진단검사의학회 CME">
<title>대한진단검사의학회 CME</title>
<link rel="icon" href="/assets/image/favicon.ico">
<link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/variable/pretendardvariable.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="/assets/css/slick.css">
<link type="text/css" rel="stylesheet" href="/assets/css/jquery-ui.min.css">
<link type="text/css" rel="stylesheet" href="/assets/css/common.css">
<script type="text/javascript" src="/assets/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/assets/js/slick.min.js"></script>
<script type="text/javascript" src="/assets/js/common.js"></script>
</head>
<body>
    <!-- 
        main일 때 calss="main"
        sub일 때 class="sub"
    -->
    <div class="wrap <?echo $main;?>">
        <div id="dim" class="js-dim"></div>
        <header id="header" class="js-header">
            <div class="header-wrap inner-layer wide">
                <h1 class="header-logo">
                    <a href="http://kslm.m2comm.co.kr/html/index.html"><img src="/assets/image/common/h1_logo.png" alt="대한진단검사의학회"></a>
                </h1>
                <nav id="gnb" class="js-gnb">
                    <ul class="gnb cf">
                        <li><a href="http://kslm.m2comm.co.kr/html/edu/list.html">수강/열람신청</a></li>
                        <li><a href="http://kslm.m2comm.co.kr/html/lib/list.html">학술자료실</a></li>
                        <li>
                            <a href="http://kslm.m2comm.co.kr/html/mypage/edu_list.html">마이페이지</a>
                            <ul>
                                <li><a href="http://kslm.m2comm.co.kr/html/mypage/edu_list.html">온라인 강의실</a></li>
                                <li><a href="http://kslm.m2comm.co.kr/html/mypage/lib_list.html">나의 자료실</a></li>
                                <li><a href="http://kslm.m2comm.co.kr/html/mypage/info.html">개인정보</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="http://kslm.m2comm.co.kr/html/bbs/notice/list.html">지원센터</a>
                            <ul>
                                <li><a href="http://kslm.m2comm.co.kr/html/bbs/notice/list.html">공지사항</a></li>
                                <li><a href="http://kslm.m2comm.co.kr/html/center/guide.html">이용가이드</a></li>
                                <li><a href="http://kslm.m2comm.co.kr/html/bbs/accordion/list.html">FAQ</a></li>
                            </ul>
                        </li>
                    </ul>
                    <a href="#n" class="btn" target="_blank">대한진단검사의학회 홈페이지 바로가기</a>
                    <button type="button" class="btn btn-menu-close js-btn-menu-close"><span class="hide">메뉴 닫기</span></button>
                </nav>
                <div class="util-menu-wrap">
                    <ul class="util-menu">
                        <li><a href="http://kslm.m2comm.co.kr/html/member/login.html">로그인</a></li>
                        <!-- <li><a href="#n">로그아웃</a></li> -->
                        <li><a href="https://www.kslm.org/intro.html" class="btn" target="_blank">대한진단검사의학회</a></li>
                    </ul>
                    <button type="button" class="btn btn-menu-open js-btn-menu-open"><span class="hide">메뉴 열기</span></button>
                </div>
            </div>
        </header>