name: Deploy to Server

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때마다 배포가 트리거됨

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 레포지토리 코드를 체크아웃

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh  # ~/.ssh 디렉토리 권한 설정
          echo "Setting up SSH key..."

          echo "Host 117.52.153.219" >> ~/.ssh/config
          echo "  Port 22006" >> ~/.ssh/config
          echo "  User kslm" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  LogLevel DEBUG3" >> ~/.ssh/config
          echo "Setting up SSH key..."

#          # Known hosts 추가
#          ssh-keyscan -H 117.52.153.219 >> ~/.ssh/known_hosts


      - name: Debug SSH connection
        run: |
          ssh -v -F ~/.ssh/config -i ~/.ssh/id_rsa -p 22006 kslm@117.52.153.219 "echo 'SSH 연결 성공!'"

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22006
            script: |
              whoami
              echo "Deploying1"
              cd /home/virtual/kslm/htdocs/kslm  # 올바른 경로로 수정
              echo "Deploying2"
              git pull origin master
              sh deploy.sh
