name: Deploy to Server

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때마다 배포가 트리거됨

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 레포지토리 코드를 체크아웃

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # 비공개 SSH 키 (GitHub Secrets에서 관리)

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p 22006 kslm@117.52.153.219 "cd /home/virtual/kslm/htdocs/kslm && git pull origin master && ./deploy.sh"
