name: Deploy to Server

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때마다 배포가 트리거됨

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 레포지토리 코드를 체크아웃

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Known hosts 추가 (보안상 서버의 호스트 키를 자동으로 추가)
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22006
            script: |
              echo "Deploying."
              cd /home/virtual/kslm/htdocs/kslm  # 올바른 경로로 수정
              git pull origin master
              sh deploy.sh
